# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uhm < Formula
  desc ""
  homepage "https://github.com/Thwani47/uhm"
  version "0.1.0"

  on_macos do
    url "https://github.com/Thwani47/uhm/releases/download/v0.1.0/uhm_0.1.0_darwin_all.tar.gz"
    sha256 "6bced0c1e30187dc22ac2e284b1fcbec1f381f6097ee506b60d71cdb77fa3edb"

    def install
      bin.install "uhm"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Thwani47/uhm/releases/download/v0.1.0/uhm_0.1.0_linux_amd64.tar.gz"
        sha256 "cb9175ffc0fc92f384f4354d7d8c1ec161d036908b4d205955b535a5001f0be8"

        def install
          bin.install "uhm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Thwani47/uhm/releases/download/v0.1.0/uhm_0.1.0_linux_arm64.tar.gz"
        sha256 "71234a2686de80a9bbebe553a83abfe5a4eabbb68ffdbb6c6df15e7e3418ec4b"

        def install
          bin.install "uhm"
        end
      end
    end
  end
end
