# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uhm < Formula
  desc ""
  homepage "https://github.com/Thwani47/uhm"
  version "0.1.3"

  on_macos do
    url "https://github.com/Thwani47/uhm/releases/download/v0.1.3/uhm_0.1.3_darwin_all.tar.gz"
    sha256 "1a33c434652f70046445a0fe8672a3a15b4530f60f78c026ba83b12e934b8de8"

    def install
      bin.install "uhm"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Thwani47/uhm/releases/download/v0.1.3/uhm_0.1.3_linux_amd64.tar.gz"
        sha256 "df6bcaa6ba9b8e0d87a448720e81b696bed20ff2bfc9529443c637a6883e8f76"

        def install
          bin.install "uhm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Thwani47/uhm/releases/download/v0.1.3/uhm_0.1.3_linux_arm64.tar.gz"
        sha256 "d04ba6eb95c6e32804db16a0110b750f72ad0e98c7fdea2328222e93a41b9fca"

        def install
          bin.install "uhm"
        end
      end
    end
  end
end
