# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uhm < Formula
  desc ""
  homepage "https://github.com/Thwani47/uhm"
  version "0.1.1"

  on_macos do
    url "https://github.com/Thwani47/uhm/releases/download/v0.1.1/uhm_0.1.1_darwin_all.tar.gz"
    sha256 "17f223a124908184b8abea0039caa0d264a6ea99f008a949d18ee3cc56219c5c"

    def install
      bin.install "uhm"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Thwani47/uhm/releases/download/v0.1.1/uhm_0.1.1_linux_amd64.tar.gz"
        sha256 "c2b10cbad4f58848469c8fa7bf4bec6859da2e6386f18e6d9164067ba2b79eb5"

        def install
          bin.install "uhm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Thwani47/uhm/releases/download/v0.1.1/uhm_0.1.1_linux_arm64.tar.gz"
        sha256 "b2a62e78a6d65a0439df0cdd193ea2362e06035f490f3d34b8b3904526cdbc8c"

        def install
          bin.install "uhm"
        end
      end
    end
  end
end
